### ISSUE TITLE
`[lib]` in `Cargo.toml` can specify its own `name`.

### ISSUE THREAD

**Issue by eddyb** [google/vk-layer-for-rust#16]
The docs suggest something like this (and mention Android):
```toml
[package]
name = "VkLayer_vendor_rust_example"

[lib]
crate-type = ["cdylib"]
```

However, changing the package name to fit a bad idea for several reasons, but also, this should work:
```toml
[lib]
name = "VkLayer_vendor_rust_example"
crate-type = ["cdylib"]
```
(relevant Cargo docs: https://doc.rust-lang.org/cargo/reference/cargo-targets.html#configuring-a-target)

Not only does it not screw with the Cargo package, but there's no reason *not* to recommend it, regardless of whether the intended target *needs it* (like Android supposedly does).

Sadly, there's a warning that the crate "should have a snake case name", that needs `#![allow(non_snake_case)]` at the crate level to hide (and then `#[warn(non_snake_case)]` on all the nested `mod`s, to avoid silencing unrelated warnings).
